<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="bblanchon.PDFium.Linux" Version="145.0.7592" />
    <PackageReference Include="PDFium.WindowsV2" Version="1.1.4" />
    <PackageReference Include="PDFiumSharp" Version="1.4660.0-alpha1" />
    <PackageReference Include="PdfPig" Version="0.1.11" />
    <PackageReference Include="PDFiumSharpV2" Version="1.1.4" />
    <PackageReference Include="Tesseract" Version="5.2.0" />
    <PackageReference Include="System.Text.Encoding.CodePages" Version="8.0.0" />
  </ItemGroup>

</Project>
